### ISSUE TITLE
Weaviate::Error: interface conversion: interface {} is int64, not int

### ISSUE THREAD

**Issue by tomas** [andreibondarev/weaviate-ruby#21]
Hi, I'm trying out your library but I'm hitting this error when running a simple query. It seems to happen because of the [$limit and $offset lines](https://github.com/andreibondarev/weaviate-ruby/blob/main/lib/weaviate/query.rb#L148-L149) in the `get_query` method. If I remove them the query works.

Running weaviate `1.19.4`, by the way.

**Comment by andreibondarev** [comment]
@tomas Would you please copy-paste the exact Ruby code you're executing?

As shown [here](https://github.com/andreibondarev/weaviate-ruby#get), I believe you need to pass in those values as strings. Wrangling the GraphQL endpoint has not been enjoyable at all.

**Comment by tomas** [comment]
Yes! You're right. Doing a `to_s` on the value for `limit` fixed the problem. A bit weird though. 

You should definitely highlight that on the project's readme!

Thanks for the quick response.

**Comment by tomas** [comment]
https://weaviate.io/developers/weaviate/api/graphql#limitations
