### ISSUE TITLE
Add Google PaLM

### ISSUE THREAD

**Issue by mattlindsey** [andreibondarev/weaviate-ruby#22]
Weaviate appears to support PaLM, so I think it can be added.

<img width="1265" alt="image" src="https://github.com/andreibondarev/weaviate-ruby/assets/5638339/62898e03-7fbe-4aad-a1f4-d3373bb2eb3e">

**Comment by andreibondarev** [comment]
@mattlindsey Let me add it real quick. Nice find!

**Comment by andreibondarev** [comment]
@mattlindsey Complete. Pushing a new gem version shortly.
